LTWeb/Areas/Admin/Controllers/CapDausController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.EF;

namespace LTWeb.Areas.Admin.Controllers
{
    public class CapDausController : BaseController
    {
        private LTWebDataContext db = new LTWebDataContext();

        // GET: Admin/CapDaus
        public async Task<ActionResult> Index()
        {
            var capDaus = db.CapDaus.Include(c => c.CLB).Include(c => c.CLB1);
            return View(await capDaus.ToListAsync());
        }

        // GET: Admin/CapDaus/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CapDau capDau = await db.CapDaus.FindAsync(id);
            if (capDau == null)
            {
                return HttpNotFound();
            }
            return View(capDau);
        }

        // GET: Admin/CapDaus/Create
        public ActionResult Create()
        {
            ViewBag.IDclbNha = new SelectList(db.CLBs, "IDclb", "TenClb");
            ViewBag.IDclbKhach = new SelectList(db.CLBs, "IDclb", "TenClb");
            return View();
        }

        // POST: Admin/CapDaus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID_capdau,IDclbNha,IDclbKhach")] CapDau capDau)
        {
            if (ModelState.IsValid)
            {
                db.CapDaus.Add(capDau);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IDclbNha = new SelectList(db.CLBs, "IDclb", "TenClb", capDau.IDclbNha);
            ViewBag.IDclbKhach = new SelectList(db.CLBs, "IDclb", "TenClb", capDau.IDclbKhach);
            return View(capDau);
        }

        // GET: Admin/CapDaus/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CapDau capDau = await db.CapDaus.FindAsync(id);
            if (capDau == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDclbNha = new SelectList(db.CLBs, "IDclb", "TenClb", capDau.IDclbNha);
            ViewBag.IDclbKhach = new SelectList(db.CLBs, "IDclb", "TenClb", capDau.IDclbKhach);
            return View(capDau);
        }

        // POST: Admin/CapDaus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID_capdau,IDclbNha,IDclbKhach")] CapDau capDau)
        {
            if (ModelState.IsValid)
            {
                db.Entry(capDau).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IDclbNha = new SelectList(db.CLBs, "IDclb", "TenClb", capDau.IDclbNha);
            ViewBag.IDclbKhach = new SelectList(db.CLBs, "IDclb", "TenClb", capDau.IDclbKhach);
            return View(capDau);
        }

        // GET: Admin/CapDaus/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CapDau capDau = await db.CapDaus.FindAsync(id);
            if (capDau == null)
            {
                return HttpNotFound();
            }
            return View(capDau);
        }

        // POST: Admin/CapDaus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            CapDau capDau = await db.CapDaus.FindAsync(id);
            db.CapDaus.Remove(capDau);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LTWeb/Areas/Admin/Views/CapDaus/Create.cshtml
@model Model.EF.CapDau

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section header{
    Tạo cặp đấu
}
@using (Html.BeginForm("Create","CapDaus",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CapDau</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_capdau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_capdau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_capdau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDclbNha, "IDclbNha", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDclbNha", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDclbNha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDclbKhach, "IDclbKhach", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDclbKhach", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDclbKhach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mói" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LTWeb/Areas/Admin/Views/CapDaus/Delete.cshtml
@model Model.EF.CapDau

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CapDau</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CLB.TenClb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLB.TenClb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLB1.TenClb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLB1.TenClb)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LTWeb/Areas/Admin/Views/CapDaus/Details.cshtml
@model Model.EF.CapDau

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section header{
    Chi tiết cặp đấu
}
<div>
    <h4>CapDau</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CLB.TenClb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLB.TenClb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLB1.TenClb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLB1.TenClb)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_capdau }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LTWeb/Areas/Admin/Views/CapDaus/Edit.cshtml
@model Model.EF.CapDau

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section header{
    Cặp nhật cặp đấu
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CapDau</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_capdau)

        <div class="form-group">
            @Html.LabelFor(model => model.IDclbNha, "IDclbNha", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDclbNha", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDclbNha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDclbKhach, "IDclbKhach", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDclbKhach", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDclbKhach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LTWeb/Areas/Admin/Views/CapDaus/Index.cshtml
@model IEnumerable<Model.EF.CapDau>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section header{
    Danh sách cặp đấu
}
<p>
    @Html.ActionLink("Tạo mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CLB.TenClb)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CLB1.TenClb)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CLB.TenClb)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CLB1.TenClb)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_capdau }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_capdau }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_capdau })
        </td>
    </tr>
}

</table>